/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;



public class App {

    public static void main(String[] args) {
      HashTable hashTable = new HashTable();

      hashTable.add("first", "this is the first message");
      hashTable.add("second", "this is the second message");
      hashTable.add("third", "test message");
      hashTable.add(3, "this is the third message");
      hashTable.add("fourth", 4);

      System.out.println(hashTable.get("first"));
    }
}
