/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion_sort;

public class App {
    public static void main(String[] args) {
      int[] arr = new int[]{5,4,1,0};
      for(int i: insertionSort(arr)){
        System.out.println(i);
      }
    }
    public static int[] insertionSort(int[] arr){
      if(arr == null){
        return null;
      }
      for(int i = 1; i<arr.length; i++){
        int j =i-1;
        int temp =  arr[i];

        while(j>=0 && temp< arr[j]){
          arr[j+1] = arr[j];
          j = j-1;
        }
        arr[j+1] = temp;
      }
      return arr;
    }
}
