/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data_structures;

public class App {
     public static void main(String[] args) {
        CreateLinkedList list = new CreateLinkedList();
        list.insert(5);
        list.insert(10);
        list.insert(20);
        list.insertAfter(5, 15);
        list.append(50);
        list.insertBefore(50, 20);
       System.out.println(list);
       try{
         System.out.println(list.fromEnd(6));
       } catch(IllegalArgumentException ex){
         System.out.println(ex.getMessage());
       }

    }
    public String getGreeting(){
       return "Hello";
    }
}
