/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data_structures;

public class App {
     public static void main(String[] args) {
        CreateLinkedList list = new CreateLinkedList();
        list.insert(5);
        list.insert(2);
        list.insert(2);
       System.out.println(list);

    }
    public String getGreeting(){
       return "Hello";
    }
}
