/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree_intersection;

import tree.BinarySearchTree;

public class App {
    public static void main(String[] args) {
      BinarySearchTree firstTree = new BinarySearchTree();
      BinarySearchTree secondTree = new BinarySearchTree();

      firstTree.add(2);
      firstTree.add(5);
      firstTree.add(10);
      firstTree.add(20);
      firstTree.add(15);

      secondTree.add(2);
      secondTree.add(4);
      secondTree.add(10);
      secondTree.add(15);
      secondTree.add(20);
      secondTree.add(50);
      System.out.println(TreeIntersection.findSameValues(firstTree, secondTree));
    }
}
