/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array_binary_search;

import java.util.Arrays;

public class App {
    public int BinarySearch(int[] array, int searchKey) {
      if(array.length > 0){
        if(array[array.length/2] == searchKey){
          return array.length/2;
        } else if(array[array.length/2] > searchKey){
          return BinarySearch(Arrays.copyOfRange(array, 0, (array.length/2) -1), searchKey);
        } else if(array[array.length/2] < searchKey){
          if(BinarySearch(Arrays.copyOfRange(array, (array.length/2) + 1, array.length),searchKey) == -1){
            return -1;
          } else{
            return BinarySearch(Arrays.copyOfRange(array, (array.length/2) + 1, array.length),searchKey) + array.length/2 + 1;
          }
        }
      }
      return -1;
    }
}
