/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayshiftlibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
  @Test public void testInsertShiftArray() {
    Library classUnderTest = new Library();
    assertArrayEquals(new int[]{2,4,5,6,8}, classUnderTest.insertShiftArray(new int[]{2,4,6,8}, 5));
    assertArrayEquals(new int[]{4,8,15,16,23,42}, classUnderTest.insertShiftArray(new int[]{4,8,15,23,42}, 16));
  }
}
