/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array_binary_search;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        int[] array = new int[]{1,2,3,4,5,6,7,8,9};
        assertTrue(classUnderTest.BinarySearch(array, 2) == 1);
        assertTrue(classUnderTest.BinarySearch(array, 5) == 4);
        assertTrue(classUnderTest.BinarySearch(array, 10) == -1);
        assertTrue(classUnderTest.BinarySearch(array, -1) == -1);
    }
}

